apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: citus-issuer
  labels:
    {{- include "citus.labels" . | nindent 4 }}
spec:
  selfSigned: { }
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: citus-cert
  labels:
    {{- include "citus.labels" . | nindent 4 }}
spec:
  secretName: citus-cert
  commonName: citus.default
  dnsNames:
  - '*.citus.default.svc.cluster.local'
  issuerRef:
    name: citus-issuer
