apiVersion: v1
kind: Service
metadata:
  name: citus
  labels:
    {{- include "citus.labels" . | nindent 4 }}
    app: citus
spec:
  selector:
    app: citus
  clusterIP: None
  ports:
  - port: 5432
    name: postgres
  - port: 6432
    name: pgbouncer

---

apiVersion: v1
kind: Service
metadata:
  name: citus-nodeport
  labels:
    {{- include "citus.labels" . | nindent 4 }}
    app: citus
spec:
  selector:
    app: citus
  ports:
  - port: 5432
    name: postgres
    nodePort: 30001
  - port: 6432
    name: pgbouncer
    nodePort: 30010
  type: NodePort
